[versions]
junit = "4.13.2"
kotlin = "2.4.0-RC"
ktor = "3.5.0"
logback = "1.5.32"

compose-multiplatform = "1.12.0-alpha01"
compose-hot-reload = "1.1.1"
icons = "1.7.3"

compose-material3 = "1.12.0-alpha01"

compose-adaptive = "1.3.0-beta01"

androidx-lifecycle = "2.11.0-beta01"
androidx-navigation = "2.10.0-alpha01"
androidx-navigation3 = "1.1.1"
androidx-navigationevent = "1.1.0"
androidx-savedstate = "1.4.0"
androidx-window = "1.5.1"

compose-markdown = "0.40.2"

composePwa = "0.6.1"

io = "0.9.0"
serialization = "1.11.0"
datetime = "0.8.0"
koog = "1.0.0-preview"
koog-beta = "1.0.0-beta-preview"

koin = "4.2.1"
koin-plugin = "1.0.0-RC2"

webpush = "1.3.0"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-testJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }

koog-agents-core = { module = "ai.koog:agents-core", version.ref = "koog" }
koog-agents-ext = { module = "ai.koog:agents-ext", version.ref = "koog" }
koog-agents-planner = { module = "ai.koog:agents-planner", version.ref = "koog" }
koog-agents-tools = { module = "ai.koog:agents-tools", version.ref = "koog" }
koog-agents-test = { module = "ai.koog:agents-test", version.ref = "koog" }

koog-llm-openai = { module = "ai.koog:prompt-executor-openai-client", version.ref = "koog-beta" }
koog-llm-anthropic = { module = "ai.koog:prompt-executor-anthropic-client", version.ref = "koog-beta" }
koog-llm-google = { module = "ai.koog:prompt-executor-google-client", version.ref = "koog-beta" }
koog-llm-ollama = { module = "ai.koog:prompt-executor-ollama-client", version.ref = "koog-beta" }
koog-llm-bedrock = { module = "ai.koog:prompt-executor-bedrock-client", version.ref = "koog-beta" }
koog-llm-deepseek = { module = "ai.koog:prompt-executor-deepseek-client", version.ref = "koog-beta" }
koog-llm-mistral = { module = "ai.koog:prompt-executor-mistralai-client", version.ref = "koog-beta" }
koog-llm-openrouter = { module = "ai.koog:prompt-executor-openrouter-client", version.ref = "koog-beta" }
koog-llms-all = { module = "ai.koog:prompt-executor-llms-all", version.ref = "koog-beta" }

koog-ktor = { module = "ai.koog:koog-ktor", version.ref = "koog-beta" }

koog-features-memory = { module = "ai.koog:agents-features-memory", version.ref = "koog-beta" }
koog-features-chat-memory-sql = { module = "ai.koog:agents-features-chat-memory-sql", version.ref = "koog-beta" }
koog-features-longterm-memory = { module = "ai.koog:agents-features-longterm-memory", version.ref = "koog-beta" }
koog-features-snapshot = { module = "ai.koog:agents-features-snapshot", version.ref = "koog-beta" }
koog-features-persistence-jdbc = { module = "ai.koog:agents-features-persistence-jdbc", version.ref = "koog-beta" }
koog-mcp-client = { module = "ai.koog:agents-mcp", version.ref = "koog-beta" }
koog-mcp-server = { module = "ai.koog:agents-mcp-server", version.ref = "koog-beta" }
koog-features-opentelemetry = { module = "ai.koog:agents-features-opentelemetry", version.ref = "koog-beta" }

kotlin-io = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "io" }
kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serialization" }
kotlin-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }

junit = { module = "junit:junit", version.ref = "junit" }

webpush = { module = "com.interaso:webpush", version.ref = "webpush" }

logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

compose-markdown = { module = "com.mikepenz:multiplatform-markdown-renderer", version.ref = "compose-markdown" }
compose-markdown-m3 = { module = "com.mikepenz:multiplatform-markdown-renderer-m3", version.ref = "compose-markdown" }

compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose-multiplatform" }
compose-runtime-saveable = { module = "org.jetbrains.compose.runtime:runtime-saveable", version.ref = "compose-multiplatform" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose-multiplatform" }
compose-ui-geometry = { module = "org.jetbrains.compose.ui:ui-geometry", version.ref = "compose-multiplatform" }
compose-ui-graphics = { module = "org.jetbrains.compose.ui:ui-graphics", version.ref = "compose-multiplatform" }
compose-ui-text = { module = "org.jetbrains.compose.ui:ui-text", version.ref = "compose-multiplatform" }
compose-ui-unit = { module = "org.jetbrains.compose.ui:ui-unit", version.ref = "compose-multiplatform" }
compose-ui-util = { module = "org.jetbrains.compose.ui:ui-util", version.ref = "compose-multiplatform" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose-multiplatform" }
compose-animation = { module = "org.jetbrains.compose.animation:animation", version.ref = "compose-multiplatform" }

compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose-multiplatform" }

compose-material = { module = "org.jetbrains.compose.material:material", version.ref = "compose-multiplatform" }
compose-material-icons-extended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "icons" }

compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "compose-material3" }
compose-material3-navigation-suite = { module = "org.jetbrains.compose.material3:material3-adaptive-navigation-suite", version.ref = "compose-material3" }

compose-adaptive-core = { module = "org.jetbrains.compose.material3.adaptive:adaptive", version.ref = "compose-adaptive" }
compose-adaptive-layout = { module = "org.jetbrains.compose.material3.adaptive:adaptive-layout", version.ref = "compose-adaptive" }
compose-adaptive-navigation = { module = "org.jetbrains.compose.material3.adaptive:adaptive-navigation", version.ref = "compose-adaptive" }
compose-adaptive-navigation3 = { module = "org.jetbrains.compose.material3.adaptive:adaptive-navigation3", version.ref = "compose-adaptive" }

androidx-lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-savedstate = { module = "org.jetbrains.androidx.savedstate:savedstate", version.ref = "androidx-savedstate" }
androidx-window-core = { module = "org.jetbrains.androidx.window:window-core", version.ref = "androidx-window" }

androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
androidx-navigation3-ui = { module = "org.jetbrains.androidx.navigation3:navigation3-ui", version.ref = "androidx-navigation3" }
androidx-navigationevent-compose = { module = "org.jetbrains.androidx.navigationevent:navigationevent-compose", version.ref = "androidx-navigationevent" }

compose-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose-multiplatform" }
compose-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose-multiplatform" }
compose-ui-test = { module = "org.jetbrains.compose.ui:ui-test", version.ref = "compose-multiplatform" }
compose-ui-test-junit4 = { module = "org.jetbrains.compose.ui:ui-test-junit4", version.ref = "compose-multiplatform" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-ktor = { module = "io.insert-koin:koin-ktor", version.ref = "koin" }
koin-ktor-logger = { module = "io.insert-koin:koin-logger-slf4j", version.ref = "koin" }

[plugins]
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
compose-hot-reload = { id = "org.jetbrains.compose.hot-reload", version.ref = "compose-hot-reload" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
koin-compiler = { id = "io.insert-koin.compiler.plugin", version.ref = "koin-plugin" }
composePwa = { id = "dev.yuyuyuyuyu.composepwa", version.ref = "composePwa" }

[bundles]
compose-core = [
    "compose-runtime", "compose-runtime-saveable", "compose-ui", "compose-foundation", "compose-animation", "compose-components-resources"
]
compose-adaptive = [
    "compose-material3", "compose-adaptive-core", "compose-adaptive-layout", "compose-adaptive-navigation", "compose-adaptive-navigation3", "compose-material3-navigation-suite"
]

compose-architecture = [
    "androidx-lifecycle-runtime-compose", "androidx-lifecycle-viewmodel-compose", "androidx-savedstate", "androidx-navigation3-ui", "androidx-navigationevent-compose", "androidx-window-core"
]